### PR TITLE
CC-1465: Change report name/dir; fix typos for params to display properly in run dialog box

### PR DESCRIPTION
**Pull request by lkvoong**

### CODE REVIEW

**Comment by cesarvh** [comment]
@lkvoong  Looks good, just a few conflicts that need to be resolved before merging.

**Comment by remillet** [comment]
@cesarvh When you get a chance, could you follow-up with Lam on this pull request tomorrow, Wednesday (4/28/2021)

**Comment by cesarvh** [comment]
@remillet  will do

**Comment by lkvoong** [comment]
re-did code changes as CC-1465b to correct conflicts from using wrong code base. See PR 73

**Pull request closed without merging**
